env:
  global:
    - secure: BGbo8RVjyQNvcyD17L4kiwOwB+CrBw1arERaaCGqW2gdzn/l0P6oQy4raoMRFjGQDBchdjgWusayjJXWcTE6CxEFAYt8rfDTC7KWF1d7XBAL9eaxCDUxNXBCdGtb2kj9Mj+CB0mIwXum0u31t3LOVY3pOKpXITcK0a6Fh1iBPw8=
before_install:
  - sudo add-apt-repository --yes ppa:hansjorg/rust
  - sudo add-apt-repository --yes ppa:cmrx64/cargo
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq rust-nightly cargo
script:
  - cargo build
  - cargo test
  - make doc
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh