[package]

name = "quicksilver"
version = "0.1.0"

authors = ["Zachary Tong <zacharyjtong@gmail.com>"]
tags = ["data structures", "approximate", "algorithms", "hyperloglog", "sketches"]

[[lib]]

name = "quicksilver"
path = "src/lib.rs"

